format = "\n$directory$git_branch$git_status$python$golang$battery$character"
right_format = "$all"
add_newline = false


[directory]
style = 'bold bg:white #000000'
truncation_length = 10
truncate_to_repo = false

[[battery.display]]
style = 'bold white'


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold blue'

[git_status]
style = 'bold blue'


[python]
format = "${symbol}${version} "
version_format = "${major}.${minor}"

[golang]
format = "${symbol}"




[cmd_duration]
disabled = true

[aws]
disabled = true

[package]
disabled = true
